[tool.black]
line-length = 88
target-version = ["py311"]
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | node_modules
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
known_first_party = ["app"]
skip = [".venv","node_modules","dist","build",".mypy_cache",".pytest_cache",".ruff_cache"]

[tool.bandit]
exclude_dirs = [".venv","node_modules","dist","build","tests","migrations"]
targets = ["app"]
