[tool.ruff]
line-length = 100
target-version = "py311"
fix = true
extend-exclude = ["**/migrations/**","**/.venv/**","**/node_modules/**","echoscript_backend_*"]

[tool.ruff.lint]
select = ["F","E","W","I","UP","B","C90","RUF100"]
ignore = ["E501","B008","B904","C901"]

[tool.ruff.lint.isort]
known-first-party = ["app"]

[tool.mypy]
python_version = "3.11"
ignore_missing_imports = true
warn_unused_ignores = true
show_error_codes = true
exclude = '(^\.venv/|/migrations/|^echoscript_backend_.*)'
