/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119917-g8087777e66-20250617"
#endif /* AVUTIL_FFVERSION_H */
